# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or whichever branch you're deploying from
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:  # Explicitly set permissions for GITHUB_TOKEN
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (optional)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # This is where your static site files (index.html, etc.) are located
